language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
matrix:
  fast_finish: true
env:
  global:
    - PHPUNIT_OPTIONS=' --colors'
before_install:
    - composer self-update
install:
    - composer install
script:
  - vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 --ignore="vendor" .
  - vendor/bin/phpunit $PHPUNIT_OPTIONS tests

notifications:
  slack:
    secure: Bt5Vn0yxz0h432TpT/yZWXlC561T1Zfr9ZpYRIKubWrHA2sPut+cDMeiFxglcaCugWREyISegGtXHqegS1ASS0sT02TuCnSFaKM2rDsdIVOON87iui8qYDkyveTLRLxgazbPy6EN6kYZclezO9U42S/TrKofiRADZhVEFURzABOSofH6SuplpxmdxYE/xRCB43mM8g9JjDRiEnrLmCYcIN/BdnNF2U8jJkWwiipUUDPfU2s6B4caQxdAI9SVwlJjX2wOLtyQ+27D64LXfbXJ7CBQN3Tt84XT6cDMR4TqQNxL785L7v3LljCHLg12M+yCcOBYmMAUMyMqFbpDGQ4ZVgdi3roNixI4pFfzkmetKBUwyFNQWgQzVKWEdqWEDQUawSYVXuvLW2EkWDWVQpb9rTpQrmX7YYA2xFWkND25AbETaAWnKyVdcjTEH+kLXZKL60n0YFNb1XlzcClI5Rs+baLwiNtAeTL0uoJptvSumrc8WPq1myegXLuhj87EDHXBeINQnIjO1ul3+qIfYIcr3uiynhQNgbrF+5DY4E2pXkKT0ibsnK4NbYBlJLQFRTyrAQ8S5YvUqa8hPtiKnr9xcgqjXO8d2jd0SgigfW9O5ZNX/VtLOcd+/7Q50yRw+ABpMm/yji+Ni6APG6spF+PNPBhsO1kUSfgXDWFZs06Lg1U=
