language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true

env:
  global:
    - PHPUNIT_OPTIONS=' --colors'

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit $PHPUNIT_OPTIONS tests
